// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ReqqQ/eventpulse-go/src/ui"
	user2 "github.com/ReqqQ/eventpulse-user-go/src/app/user"
	"github.com/ReqqQ/eventpulse-user-go/src/domain/user"
	"github.com/ReqqQ/eventpulse-user-go/src/infrastructure/users"
	"github.com/ReqqQ/eventpulse-user-go/src/shared"
	"github.com/google/wire"
)

// Injectors from di_container.go:

func InitDIContainer() ui.Server {
	factory := user.BuildFactory()
	repository := users.CreateRepository(factory)
	userHandler := user2.CreateQueryHandler(repository)
	bus := shared.CreateUserBusInstance(userHandler)
	userApp := ui.BuildUserApp(bus)
	app := ui.BuildApp(userApp)
	server := ui.BuildServer(app)
	return server
}

// di_container.go:

var buildUserApp = wire.NewSet(shared.CreateUserBusInstance, user2.CreateQueryHandler, users.CreateRepository, user.BuildFactory)
