// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ReqqQ/eventpulse-go/src/ui"
	"github.com/ReqqQ/eventpulse-user-go/app/user"
)

// Injectors from di_container.go:

func InitDIContainer() ui.Controllers {
	userService := user.BuildUserService()
	userController := ui.BuildUserController(userService)
	controllers := ui.BuildControllers(userController)
	return controllers
}
