version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs  # Mount certificates
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # HAProxy config file
    networks:
      - app_network
    depends_on:
      - scylla
      - kafka

  scylla:
    image: scylladb/scylla:latest
    container_name: eventpulse-scylla
    environment:
      - SCYLLA_DB_USER=eventpulse
      - SCYLLA_DB_PASSWORD=eventpulsepassword
      - SCYLLA_DB_NAME=eventpulse
    volumes:
      - scylla_data:/var/lib/scylla  # Persistent volume for ScyllaDB data
    networks:
      - app_network
    ports:
      - "9042:9042"  # CQL port for connecting to ScyllaDB
      - "9160:9160"  # Thrift port

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_network
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app_network
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  kadeck:
    image: xeotek/kadeck:5.3.0
    container_name: kadeck
    environment:
      - xeotek_kadeck_free=nevvgaming@gmail.com
      - xeotek_kadeck_port=90
    networks:
      - app_network
    ports:
      - "90:90"
    volumes:
      - kadeck_data:/root/.kadeck/

networks:
  app_network:
    driver: bridge

volumes:
  scylla_data:
    external: false
  zookeeper_data:
    external: false
  kafka_data:
    external: false
  kadeck_data:     # Define kadeck_data here
    external: false