version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    container_name: vue-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: npm run dev
    networks:
      - app_network

  backend:
    build:
      context: ../       # Kontekst budowania obejmuje cały projekt, w tym folder eventpulse-user-go
      dockerfile: ./backend/Dockerfile  # Użyj Dockerfile z katalogu backend
    container_name: go-backend
    ports:
      - "8080:8080"
    volumes:
      - ../backend:/app
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: eventpulse-db
    environment:
      POSTGRES_USER: eventpulse
      POSTGRES_PASSWORD: eventpulsepassword
      POSTGRES_DB: eventpulse
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: eventpulse-nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: