version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs  # Mount certificates
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # HAProxy config file
    networks:
      - app_network
    depends_on:
      - backend  # Ensure HAProxy waits for backend service

  backend:
    build:
      context: ./  # Path to your Go backend Dockerfile
      dockerfile: Dockerfile  # Dockerfile for Go backend
    container_name: go-backend
    networks:
      - app_network
    environment:
      - DB_HOST=eventpulse-db
      - DB_USER=eventpulse
      - DB_PASSWORD=eventpulsepassword
      - DB_NAME=eventpulse
    depends_on:
      - db  # Ensure Go waits for database service

  db:
    image: postgres:latest
    container_name: eventpulse-db
    environment:
      POSTGRES_USER: eventpulse
      POSTGRES_PASSWORD: eventpulsepassword
      POSTGRES_DB: eventpulse
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistent volume for database
    networks:
      - app_network
    ports:
      - "5432:5432"

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    external: false  # This will create a persistent volume managed by Docker