// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	factory3 "github.com/ReqqQ/eventpulse-go/src/infrastructure/user/factory"
	"github.com/ReqqQ/eventpulse-go/src/ui/routes"
	"github.com/ReqqQ/eventpulse-user-go/src/app/user/command"
	"github.com/ReqqQ/eventpulse-user-go/src/app/user/handler"
	"github.com/ReqqQ/eventpulse-user-go/src/app/user/query"
	"github.com/ReqqQ/eventpulse-user-go/src/domain/user/factory"
	"github.com/ReqqQ/eventpulse-user-go/src/domain/user/service"
	"github.com/ReqqQ/eventpulse-user-go/src/infrastructure/facebook"
	factory2 "github.com/ReqqQ/eventpulse-user-go/src/infrastructure/users/factory"
	"github.com/ReqqQ/eventpulse-user-go/src/infrastructure/users/repository"
	"github.com/ReqqQ/eventpulse-user-go/src/shared"
	"github.com/google/wire"
)

// Injectors from di_container.go:

func InitDIContainer() routes.Routes {
	factoryFactory := factory.BuildFactory()
	userRepository := repository.BuildUserRepository(factoryFactory)
	facebookRepository := facebook.BuildApiFacebookRepository()
	serviceService := service.BuildService()
	userFactory := factory2.BuildUserFactory()
	userQueryHandler := query.BuildUserQueryHandler(userRepository, facebookRepository, serviceService, userFactory)
	userCommandHandler := command.BuildCommandQueryHandler()
	userBus := handler.BuildUserBus(userQueryHandler, userCommandHandler)
	bus := shared.BuildBus(userBus)
	factoryUserFactory := factory3.BuildFactory()
	routesRoutes := routes.BuildRoutes(bus, factoryUserFactory)
	return routesRoutes
}

// di_container.go:

// var userInterfaceFacebookRepository = wire.NewSet(
//
//	userInfrastructureFacebook.BuildApiFacebookRepository,
//	wire.Bind(new(appUser.FacebookRepository), new(userInfrastructureFacebook.ApiFacebookRepository)),
//
// )
var buildUserApp = wire.NewSet(query.BuildUserQueryHandler, command.BuildCommandQueryHandler, repository.BuildUserRepository, factory.BuildFactory, facebook.BuildApiFacebookRepository, service.BuildService, factory2.BuildUserFactory)
